### ISSUE TITLE
好像不行了？

### ISSUE THREAD

**Issue by wby238** [shimachao/zhihuzhuanlan2pdf#1]
测试网址：https://zhuanlan.zhihu.com/c_80131470
```log
Traceback (most recent call last):
  File "start.py", line 55, in <module>
    zhuanlan_to_pdf(slug)
  File "start.py", line 31, in zhuanlan_to_pdf
    cover, article_list = zl.get_result()
  File "G:\git\zhihuzhuanlan2pdf\zhuanlan.py", line 80, in get_result
    return self._get_cover(), self._get_article_list()
  File "G:\git\zhihuzhuanlan2pdf\zhuanlan.py", line 74, in _get_article_list
    article_list.append(article.get_article_html(url=url))
  File "G:\git\zhihuzhuanlan2pdf\article.py", line 156, in get_article_html
    self.get_article_dict(url=url)
  File "G:\git\zhihuzhuanlan2pdf\article.py", line 37, in get_article_dict
    json_obj = session.get(url=url).json()[0]
IndexError: list index out of range
```

**Comment by wby238** [comment]
用readme上的网址倒是抓取成功，但效果跟readme上的差很远，log如下：
```log
Loading pages (1/6)
Warning: Failed to load file:///G:/git/zhihuzhuanlan2pdf/out/css/zhuanlan.css (ignore)
libpng warning: iCCP: known incorrect sRGB profile           ] 29%
Warning: Failed to load file://zhstatic.zhihu.com/assets/zhihu/ztext/whitedot.jpg (ignore)
libpng warning: iCCP: known incorrect sRGB profile           ] 79%
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

**Comment by yjhjstz** [comment]
不是readme 的例子不行了。
