### ISSUE TITLE
知乎网页改版无法使用

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [shimachao/zhihuzhuanlan2pdf#4]
Traceback (most recent call last):
  File "start.py", line 55, in <module>
    zhuanlan_to_pdf(slug)
  File "start.py", line 31, in zhuanlan_to_pdf
    cover, article_list = zl.get_result()
  File "/Users/yinhan/Downloads/zhihuzhuanlan2pdf-master/zhuanlan.py", line 80, in get_result
    return self._get_cover(), self._get_article_list()
  File "/Users/yinhan/Downloads/zhihuzhuanlan2pdf-master/zhuanlan.py", line 64, in _get_cover
    self._get_zhuanlan_info()
  File "/Users/yinhan/Downloads/zhihuzhuanlan2pdf-master/zhuanlan.py", line 46, in _get_zhuanlan_info
    self.zhuanlan_dict['avatar'] = json_obj['avatar']['template'].replace('{id}', json_obj['avatar']['id']).\
KeyError: 'avatar'

**Comment by yegbert** [comment]
我也遇到相同的问题……

**Comment by TRISTANDDD** [comment]
t同样是这个问题，想问问怎么办

**Comment by shimachao** [comment]
> t同样是这个问题，想问问怎么办

等我有时间更新一下，现在996确实没多少时间维护

**Comment by TRISTANDDD** [comment]
哈哈哈好的谢谢老板



     
 






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shimachao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 下午4:34
收件人:&nbsp;"shimachao/zhihuzhuanlan2pdf"<zhihuzhuanlan2pdf@noreply.github.com&gt;;
抄送:&nbsp;"邸欣雨"<510621849@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [shimachao/zhihuzhuanlan2pdf] 知乎网页改版无法使用 (#4)





  
t同样是这个问题，想问问怎么办
  
等我有时间更新一下，现在996确实没多少时间维护
